#!/bin/bash

set -e

if [ $# -eq 0 ] 
then
    branch=`get_tracked_remote_branch.sh`
else
    branch=$1
fi

old_stash=$(git rev-parse -q --verify refs/stash || echo '')
git stash
new_stash=$(git rev-parse -q --verify refs/stash || echo '')

set +x
git rebase -i remotes/$branch
if [ "$old_stash" != "$new_stash" ] 
then 
    git stash pop
fi

exit
